### ISSUE TITLE
Color column 

### ISSUE THREAD

**Issue by make-it-happen-p** [datapythonista/bollywood_workshop#4]
In the color column "array(['Color', None, 'Color Black and White', 'Black and WhiteColor',
       'ColorColor', 'Black and White', 'ColorColorColor',
       'Color Black and WhiteColor', 'Black and White Black and White'], dtype=object)"
these are the unique values .But as you said there are only two colors "Color" or "Black and White Color"
so how can i perform this .
Another thing is that None values are also there .So these also need to be removed or not ?

**Comment by datapythonista** [comment]
Not sure how I did that, there are many ways, but you should have my approach in the appendix notebook.

**Comment by datapythonista** [comment]
You have it in the third cell of the appendix:
```
imdb['color'] = imdb['color'].replace({'ColorColor': 'Color',
                                       'ColorColorColor': 'Color',
                                       'Black and White Black and White': 'Black and White'})
imdb['color'] = imdb['color'].where(imdb.color.isin(['Color', 'Black and White']), float('NaN'))
```
